### ISSUE TITLE
Make this plugin universal

### ISSUE THREAD

**Issue by avxkim** [gissehel/Wox-UnitConverter#1]
Possible to add currency converter also?

**Comment by hidara2000** [comment]
I agree. I would love to be able to add conversions. eg Celcius to Fahrenheit etc. I've tried the export feature but always get a blank document. Cheers

**Comment by gissehel** [comment]
About currency conversion: It would make it much more complex to handle as physical units and money are totally different concepts

**Comment by gissehel** [comment]
@hidara2000 : 
About Celcius and Fahrenheit aren't really units for temperature but are degree. While Kelvin is a unit for temperature.

It means that "it's not as simple". While you can say that

- 1°C = 274.15 K
- 1°C/s = 1 K/s

So °C or °F doesn't behave like a unit but more like a degree.

**Comment by gissehel** [comment]
@hidara2000:
About export, the plugin will export all the "custom units" you've defined, and all the custom prefix you've defined. If the file is empty, you didn't define any.

Both aren't documented yet on the main page. You can type:
```
unit tatami = 1.5488 m2
```
It will define a tatami (japanese unit for surface, specially used for room size).

You can also type:
```
unit kk ~ 1012[compromisekilo]
```
to define "kk" as being a new prefix of value 1012 which is a comprise between the 1000 kilo and the 1024 kilo. ( As stated in https://www.xkcd.com/394/ )

You'll then be able to use kks as being 1012 seconds.

**Comment by hidara2000** [comment]
Cheers for the reply.
